---
- hosts: localhost
  user: naser
  tasks:
  - name: clone repositories and create vms
    include_role:
      name: genscape
      tasks_from: "{{ item }}"
    with_items:
      - clone.yml
      - vm-creation.yml
      - public-key.yml   
  
  - pause:
      minutes: 2

- hosts: dockerswarmcluster
  user: vagrant
  become: yes
  tasks:
  - name: install docker to vms
    import_role:
      name: genscape
      tasks_from: docker-installation.yml

  - pause:
      minutes: 2

- hosts: manager-1
  user: vagrant
  tasks:
  - name: init manager, extract token
    import_role:
      name: genscape
      tasks_from: docker-swarm.yml
  - name: Copy docker-compose-stack.yml to manager-1
    copy:
      src: "{{ local_user_path }}/devops"
      dest: "{{ remote_user_path }}"
      owner: vagrant
      group: vagrant
      mode: u=rw,g=r,o=r
  # - name: Remove a swarm manager
  #   docker_swarm:
  #     state: absent
  #     force: true

- hosts: manager-2, manager-3
  user: vagrant
  tasks:  
  - name: join  manager2 & 3
    import_role:
      name: genscape
      tasks_from: docker-swarm-join-manager.yml
#   # - name: Leave swarm for a node
#   #   docker_swarm:
#   #     state: absent
#   #     force: true

  - pause:
      minutes: 2

- hosts: worker-1, manager-3
  user: vagrant
  tasks:  
  - name: join  worker
    import_role:
      name: genscape
      tasks_from: docker-swarm-join-worker.yml

- hosts: manager-1
  user: vagrant
  tasks:  
  - name: deploy stack
    import_role:
      name: genscape
      tasks_from: deploy-stack.yml