---

# - hosts: dockerswarmcluster
#   become: yes
#   user: "{{ remote_user }}"
#   vars:
#     remote_user: vagrant
#   tasks:
#     - name: init manager, manager and worker token extracted
#       import_role:
#         name: genscape
#         tasks_from: docker-installation.yml

- hosts: manager-1
  user: vagrant
  tasks:
  - name: init manager, manager and worker token extracted
    import_role:
      name: genscape
      tasks_from: docker-swarm.yml
    
- hosts: manager-2
  user: vagrant
  tasks:  
  - name: join  manager2 & 3
    import_role:
      name: genscape
      tasks_from: docker-swarm-join-manager.yml